services:
  - type: web
    name: majid-telegram-bot
    env: python
    buildCommand: "pip install -r majid/requirements.txt && pip install gevent"
    startCommand: "python -m gunicorn --bind 0.0.0.0:$PORT --worker-class gevent --workers 1 --preload --timeout 60 majid.wsgi:flask_app --env WEBHOOK_URL=https://mnr-zwzy.onrender.com --env GUNICORN_CMD_ARGS='--worker-tmp-dir /dev/shm'"
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
    healthCheckPath: /
    healthCheckInterval: 30s
    healthCheckTimeout: 10s
    healthCheckFailureThreshold: 5
    healthCheckSuccessThreshold: 2
    autoDeploy: true
    pullRequestDeploy: true
    plan: free
    disk: 
      name: data-disk
      mountPath: /home/ubuntu/majid_bot/majid/data.json
      sizeGB: 1
