services:
  - type: web
    name: majid-telegram-bot
    env: python
    buildCommand: "pip install -r majid/requirements.txt"
    startCommand: "WEBHOOK_URL=https://<YOUR_RENDER_SERVICE_URL> python majid/main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
    healthCheckPath: /
    healthCheckInterval: 30s
    healthCheckTimeout: 10s
    healthCheckFailureThreshold: 5
    healthCheckSuccessThreshold: 2
    autoDeploy: true
    pullRequestDeploy: true
    plan: free
    disk: 
      name: data-disk
      mountPath: /home/ubuntu/majid_bot/majid/data.json
      sizeGB: 1
